### ISSUE TITLE
Error when running demo?

### ISSUE THREAD

**Issue by salahzoubi** [radekd91/inferno#7]
Followed all the instructions to get the environment running, I've also ran the submodules (optional) script at the start of the instructions. Whenever I try to run the demo, I get the following: 

> Could not import SPECTRE. Make sure you pull the repository with submodules to enable SPECTRE.
> Traceback (most recent call last):
>   File "/home/ubuntu/inferno/inferno/models/temporal/external/SpectrePreprocessor.py", line 16, in <module>
>     from spectre.src.spectre import SPECTRE
> ModuleNotFoundError: No module named 'spectre'
> 
> Could not import EmoSwinModule. SWIN models will not be available. Make sure you pull the repository with submodules to enable SWIN.
> Could not import EmoSwinModule. SWIN models will not be available. Make sure you pull the repository with submodules to enable SWIN.
> SWIN not found, will not be able to use SWIN models
> Traceback (most recent call last):
>   File "demos/demo_eval_talking_head_on_audio.py", line 21, in <module>
>     from inferno_apps.TalkingHead.evaluation.evaluation_functions import *
>   File "/home/ubuntu/inferno/inferno_apps/TalkingHead/evaluation/evaluation_functions.py", line 35, in <module>
>     from psbody.mesh import Mesh
>   File "/home/ubuntu/miniconda3/envs/work38/lib/python3.8/site-packages/psbody/mesh/__init__.py", line 10, in <module>
>     from .meshviewer import MeshViewer, MeshViewers
>   File "/home/ubuntu/miniconda3/envs/work38/lib/python3.8/site-packages/psbody/mesh/meshviewer.py", line 49, in <module>
>     from OpenGL import GL, GLU, GLUT
>   File "/home/ubuntu/miniconda3/envs/work38/lib/python3.8/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
>     from OpenGL.GLUT.fonts import *
>   File "/home/ubuntu/miniconda3/envs/work38/lib/python3.8/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
>     p = platform.getGLUTFontPointer( name )
>   File "/home/ubuntu/miniconda3/envs/work38/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 350, in getGLUTFontPointer
>     raise NotImplementedError( 
> NotImplementedError: Platform does not define a GLUT font retrieval function

Any suggestions where I may be going wrong?
Thank you!

**Comment by radekd91** [comment]
@salahzoubi , thanks for your interest. 

SPECTRE should not be necessary to run the model so you can ignore that error. 

It seems your error comes from a problem with OpenGL. This can be a tricky part and I can only provide limited assistance there.  
What platform are  you on? The codebase was tested on Ubuntu 20.04 with OpenGL and also on headless Ubuntu with EGL. 

It appears your platform doesn't have either. What platform are you on? Is it headless? What is the value of the DISPLAY env variable?

The code won't be runnable if OpenGL is not set up properly. If you want to bypass opengl, this is doable. The code only uses it for final visualizations. You can try commenting out the import to psbody.mesh and dump the meshes in some other way.

**Comment by salahzoubi** [comment]
Thanks for getting back to me so quickly @radekd91. 

I'm running headless Ubuntu 20.04 (EC2 instance) with no DISPLAY variable (returns nothing since its a remote server). What would be the best course of action in this case?

**Comment by radekd91** [comment]
This is tricky. There's a few ways forward.

1) somehow install EGL on your headless instance
2) try to use virtual display and non accelerated opengl rendering
3) comment out the rendering import and only dump meshes or find another
way to render, such as using pytorch3D

No way out I'm afraid. OpenGL and headless servers are not always best
friends

**Comment by radekd91** [comment]
So I pushed a small fix, please reinstall the psbody-mesh library from the following repo: 
```
pip install git+https://github.com/radek91/mesh.git@fix/openGLunavailable
```
It won't enable OpenGL but at least the psbody-mesh Mesh class will work even if OpenGL fails

**Comment by cucdengjunli** [comment]
mark

**Comment by zhangliyun9120** [comment]
> So I pushed a small fix, please reinstall the psbody-mesh library from the following repo:
> 
> ```
> pip install git+https://github.com/radek91/mesh.git@fix/openGLunavailable
> ```
> 
> It won't enable OpenGL but at least the psbody-mesh Mesh class will work even if OpenGL fails

Dear @radekd91 ，this cmd seems not work since it does not exist. Could you please refer to the below errors and give some advice, thx so much.

![Weixin Image_20240504215057](https://github.com/radekd91/inferno/assets/23353228/2bd84b8c-b62e-4ca2-ac20-5ecf314673ff)

**Comment by zhangliyun9120** [comment]
> So I pushed a small fix, please reinstall the psbody-mesh library from the following repo:
> 
> ```
> pip install git+https://github.com/radek91/mesh.git@fix/openGLunavailable
> ```
> 
> It won't enable OpenGL but at least the psbody-mesh Mesh class will work even if OpenGL fails

the correct cmd should be "radekd91" not "radek91" ...

**Comment by yinfan-24** [comment]
I encountered the same error. It seems to occur during the final rendering and composition of the video. Importing the obj files from "M005_Happy_0/meshes" into Blender works fine.

**Comment by Scaryplasmon** [comment]
i confirm what [zhangliyun9120](https://github.com/zhangliyun9120) suggested, thanks!

run

`pip install git+https://github.com/radekd91/mesh.git@fix/openGLunavailable`

to install psbody-mesh correctly

**Comment by radekd91** [comment]
Good catch, guys! Thanks. I pushed a fix
